-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 23:20:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siab` DEFAULT CHARACTER SET utf8 ;
USE `siab` ;

-- -----------------------------------------------------
-- Table `siab`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`municipios` (
  `codMunicipio` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codMunicipio`),
  UNIQUE INDEX `unique_ufMun` (`nome` ASC, `uf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`fichaA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`fichaA` (
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `segmento` INT NOT NULL,
  `dt_cadastro` DATE NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`municipio`, `area`, `microarea`, `codFamilia`),
  INDEX `index_municipio_fichaA` (`municipio` ASC) VISIBLE,
  INDEX `index_area_fichaA` (`area` ASC) VISIBLE,
  INDEX `index_microArea_fichaA` (`microarea` ASC) VISIBLE,
  INDEX `index_codFamilia_fichaA` (`codFamilia` ASC) INVISIBLE,
  CONSTRAINT `fk_codMunicipio_fichaA`
    FOREIGN KEY (`municipio`)
    REFERENCES `siab`.`municipios` (`codMunicipio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`MembrosFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`MembrosFamilia` (
  `codPessoa` INT NOT NULL AUTO_INCREMENT,
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `dt_nascimento` DATE NULL,
  `idade` INT NOT NULL,
  `sexo` VARCHAR(100) NOT NULL,
  `situacaoEscolar` VARCHAR(50) NOT NULL,
  `ocupacao` VARCHAR(100) NULL,
  PRIMARY KEY (`codPessoa`),
  INDEX `index_codPessoa_pessoas` (`codPessoa` ASC) VISIBLE,
  INDEX `fk_MembrosFamilia_fichaA1_idx` (`municipio` ASC, `area` ASC, `microarea` ASC, `codFamilia` ASC) INVISIBLE,
  UNIQUE INDEX `unique_membro` (`codPessoa` ASC, `municipio` ASC, `area` ASC, `microarea` ASC, `codFamilia` ASC) VISIBLE,
  CONSTRAINT `fk_MembrosFamilia_fichaA1`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaA` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`condicoesMembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`condicoesMembros` (
  `codPessoa` INT NOT NULL,
  `condicaoOuDoenca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codPessoa`, `condicaoOuDoenca`),
  CONSTRAINT `fk_codPessoa_cond`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `siab`.`MembrosFamilia` (`codPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`situacaoFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`situacaoFamilia` (
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `tipoCasa` VARCHAR(60) NOT NULL,
  `num_comodos` INT NOT NULL,
  `destino_lixo` VARCHAR(45) NOT NULL,
  `tratamento_agua` VARCHAR(45) NOT NULL,
  `abastecimento_agua` VARCHAR(45) NOT NULL,
  `destino_fezesUrina` VARCHAR(45) NOT NULL,
  `energiaEletrica` TINYINT NOT NULL,
  PRIMARY KEY (`municipio`, `area`, `microarea`, `codFamilia`),
  CONSTRAINT `fk_situacao_fichaA`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaA` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`planosSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`planosSaude` (
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `nomePlanoDeSaude` VARCHAR(80) NOT NULL,
  `numeroPessoa` INT NOT NULL,
  PRIMARY KEY (`municipio`, `area`, `microarea`, `codFamilia`),
  CONSTRAINT `fk_OutrasInformacoes_fichaA1`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaA` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`informacoesFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`informacoesFamilia` (
  `codInformacao` INT NOT NULL AUTO_INCREMENT,
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `observacao` VARCHAR(300) NULL,
  PRIMARY KEY (`codInformacao`),
  UNIQUE INDEX `fichaA_UNIQUE` (`codFamilia` ASC, `microarea` ASC, `area` ASC, `municipio` ASC) INVISIBLE,
  CONSTRAINT `fk_informacoesFamilia_fichaA1`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaA` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`infoCasoDoenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`infoCasoDoenca` (
  `codInformacao` INT NOT NULL,
  `item` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codInformacao`, `item`),
  CONSTRAINT `fk_informacoesCasoDoenca_informacoesFamilia1`
    FOREIGN KEY (`codInformacao`)
    REFERENCES `siab`.`informacoesFamilia` (`codInformacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`infoMeiosComunicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`infoMeiosComunicacao` (
  `codInformacao` INT NOT NULL,
  `item` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codInformacao`, `item`),
  CONSTRAINT `fk_infoMeiosComunicacao_informacoesFamilia1`
    FOREIGN KEY (`codInformacao`)
    REFERENCES `siab`.`informacoesFamilia` (`codInformacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`infoGruposComunitarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`infoGruposComunitarios` (
  `codInformacao` INT NOT NULL,
  `item` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codInformacao`, `item`),
  CONSTRAINT `fk_infoGruposComunitarios_informacoesFamilia1`
    FOREIGN KEY (`codInformacao`)
    REFERENCES `siab`.`informacoesFamilia` (`codInformacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`infoMeiosTransporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`infoMeiosTransporte` (
  `codInformacao` INT NOT NULL,
  `item` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codInformacao`, `item`),
  CONSTRAINT `fk_infoMeiosTransporte_informacoesFamilia1`
    FOREIGN KEY (`codInformacao`)
    REFERENCES `siab`.`informacoesFamilia` (`codInformacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`fichaB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`fichaB` (
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `anoCorrente` INT NOT NULL,
  `nomeAgente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`municipio`, `area`, `microarea`, `codFamilia`),
  CONSTRAINT `fk_fichaB_fichaA1`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaA` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siab`.`acompanhamento__H`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siab`.`acompanhamento__H` (
  `municipio` INT NOT NULL,
  `area` INT NOT NULL,
  `microarea` INT NOT NULL,
  `codFamilia` INT NOT NULL,
  `codMembro` INT NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `dia_visita` VARCHAR(45) NOT NULL,
  `faz_dieta` ENUM("Sim", "Não") NOT NULL,
  `toma_medicacao` ENUM("Sim", "Não") NOT NULL,
  `faz_exercicios_fisicos` ENUM("Sim", "Não") NOT NULL,
  `pressao_arterial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`municipio`, `area`, `microarea`, `codFamilia`, `codMembro`),
  INDEX `fk_acompanhamento__H_MembrosFamilia1_idx` (`codMembro` ASC) VISIBLE,
  CONSTRAINT `fk_acompanhamento__H_fichaB1`
    FOREIGN KEY (`municipio` , `area` , `microarea` , `codFamilia`)
    REFERENCES `siab`.`fichaB` (`municipio` , `area` , `microarea` , `codFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acompanhamento__H_MembrosFamilia1`
    FOREIGN KEY (`codMembro`)
    REFERENCES `siab`.`MembrosFamilia` (`codPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
